#!/bin/bash

if [ $# -eq 0 ]; then
    php -dxdebug.remote_enable=1 -dxdebug.remote_autostart=1 vendor/bin/phpunit --colors=always
else
    php -dxdebug.remote_enable=1 -dxdebug.remote_autostart=1 vendor/bin/phpunit --colors=always --filter=$1
fi
